#if TOOLS
using Godot;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Anvil.Editor;

internal static class AnvilGenerator
{
    public static void GenerateAndSave(List<ForgeData> targets)
    {
        string[] userExtensions = AnvilSettings.GetValidExtensions();
        HashSet<string> validExtensions = [.. userExtensions.Select(ext => ext.ToLower())];

        var groupedTargets = targets.GroupBy(t => t.OuterClass);

        foreach (var group in groupedTargets)
        {
            string outerClassName = group.Key;
            string namespaceName = group.First().Namespace;
            
            bool hasNamespace = !string.IsNullOrEmpty(namespaceName);

            StringBuilder sb = new();

            sb.AppendLine("// AUTO-GENERATED BY ANVIL PLUGIN - DO NOT EDIT");
            sb.AppendLine("using Godot;");
            sb.AppendLine("using System;");
            sb.AppendLine();

            if (hasNamespace)
                sb.AppendLine($"namespace {namespaceName};");

            string ind1 = "    ";
            string ind2 = ind1 + "    ";

            sb.AppendLine();
            sb.AppendLine($"public partial class {outerClassName}");
            sb.AppendLine($"{{");

            foreach (var target in group)
            {
                sb.AppendLine($"{ind1}public static partial class {target.InnerClass}");
                sb.AppendLine($"{ind1}{{");

                string dirPath = ProjectSettings.GlobalizePath(target.ResourcePath);
                List<string> generatedNames = [];

                if (Directory.Exists(dirPath))
                {
                    var searchOption = target.Recursive ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;

                    var files = Directory.GetFiles(dirPath, "*", searchOption)
                        .Where(f => !f.EndsWith(".import"))
                        .Where(f => validExtensions.Contains(Path.GetExtension(f).ToLower()));

                    var seenNames = new HashSet<string>();

                    foreach (var file in files)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(file);
                        string pascalCaseName = fileName.ToPascalCase();

                        if (!seenNames.Add(pascalCaseName))
                        {
                            GD.PushWarning($"Anvil: Skipped duplicate ID '{pascalCaseName}' from '{file}' " +
                                           $"(name collision within '{target.ResourcePath}' after recursive scan).");
                            continue;
                        }

                        if (fileName.Contains(','))
                        {
                            GD.PushWarning($"Anvil: '{fileName}' contains a comma and was excluded from ENUM_NAMES " +
                                           $"(would corrupt the enum hint string).");
                        }
                        else
                        {
                            generatedNames.Add(fileName);
                        }

                        sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{fileName}\";");
                    }
                }
                else
                {
                    GD.PushError($"Anvil: Directory not found at {target.ResourcePath}");
                }

                sb.AppendLine();
                sb.AppendLine($"{ind2}public const string EnumNames = \"{string.Join(',', generatedNames)}\";");

                sb.AppendLine($"{ind1}}}");
                sb.AppendLine();
            }

            sb.AppendLine($"}}");
            AnvilFileIO.SaveGeneratedFile(outerClassName, sb.ToString());
        }
    }
}
#endif
