using Godot;
using Anvil; // Namespace of the plugin

namespace Examples;

public partial class Audio : Node
{
    //You can export a list of generated ids for a specific use.

    /*
    [Export(PropertyHint.Enum, Audio.AllNames.EnumNames)]
    public string CurrentAudio { get; set; }

    [Export(PropertyHint.Enum, Audio.MusicNames.EnumNames)]
    public string CurrentMusic { get; set; }

    [Export(PropertyHint.Enum, Audio.SfxNames.EnumNames)]
    public string CurrentSfx { get; set; }
    */

    // Works as a storage for sfx ids
    [Forge("res://examples/audio_files/sfx/")]
    public static partial class SfxNames;

    // Works as a storage for music ids
    [Forge("res://examples/audio_files/music/")]
    public static partial class MusicNames;

    // Works as a storage for all audio ids (recursive supported)
    [Forge("res://examples/audio_files/", recursive: true)]
    public static partial class AllNames;
}

// Generated Script would look like this :

/*
// AUTO-GENERATED BY ANVIL PLUGIN - DO NOT EDIT
using Godot;
using System;

namespace Examples;

public partial class Audio
{
    public static partial class SfxNames
    {
        public static readonly StringName Digging = "digging";
        public static readonly StringName Planted = "planted";
        public static readonly StringName RockHit = "rock_hit";
        public static readonly StringName TreeFalling = "tree_falling";
        public static readonly StringName TreeHit = "tree_hit";
        public static readonly StringName WaterCan = "water_can";

        public const string EnumNames = "digging,planted,rock_hit,tree_falling,tree_hit,water_can";
    }

    public static partial class MusicNames
    {
        public static readonly StringName GentleBreeze = "gentle_breeze";
        public static readonly StringName GoldenGleam = "golden_gleam";

        public const string EnumNames = "gentle_breeze,golden_gleam";
    }

    public static partial class AllNames
    {
        public static readonly StringName GentleBreeze = "gentle_breeze";
        public static readonly StringName GoldenGleam = "golden_gleam";
        public static readonly StringName Digging = "digging";
        public static readonly StringName Planted = "planted";
        public static readonly StringName RockHit = "rock_hit";
        public static readonly StringName TreeFalling = "tree_falling";
        public static readonly StringName TreeHit = "tree_hit";
        public static readonly StringName WaterCan = "water_can";

        public const string EnumNames = "gentle_breeze,golden_gleam,digging,planted,rock_hit,tree_falling,tree_hit,water_can";
    }

}
*/
