#if TOOLS
using Godot;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Anvil;

public static class AnvilGenerator
{
    private static readonly HashSet<string> ExcludedExtensions = [".import", ".uid"];

    public static void GenerateAndSave(AnvilRuleSet rules)
    {
        List<AnvilRule> validRules = AnvilValidator.ValidateRules(rules);

        StringBuilder sb = new();

        sb.AppendLine("// AUTO-GENERATED BY ANVIL PLUGIN - DO NOT EDIT");
        sb.AppendLine("using Godot;");
        sb.AppendLine();
        sb.AppendLine("namespace Anvil;");
        sb.AppendLine();
        sb.AppendLine("public static partial class Storage");
        sb.AppendLine("{");

        AppendGlobalGroupsClass(sb);
        AppendInputActionsClass(sb);
        AppendAudioBusesClass(sb);

        foreach (var rule in validRules)
        {
            AppendFolderClass(sb, rule);
        }

        sb.AppendLine("}");

        AnvilFileIO.SaveGeneratedFile("Storage", sb.ToString());
    }

    private static void AppendAudioBusesClass(StringBuilder sb)
    {
        string ind1 = "    ";
        string ind2 = ind1 + "    ";

        sb.AppendLine($"{ind1}public static class AudioBuses");
        sb.AppendLine($"{ind1}{{");

        List<string> busNames = [];
        var seenNames = new HashSet<string>();

        int busCount = AudioServer.GetBusCount();
        for (int i = 0; i < busCount; i++)
        {
            string busName = AudioServer.GetBusName(i);
            if (string.IsNullOrWhiteSpace(busName))
                continue;

            string pascalCaseName = busName.ToPascalCase();

            if (!seenNames.Add(pascalCaseName))
            {
                GD.PushWarning($"Anvil: Skipped duplicate audio bus ID '{pascalCaseName}' from '{busName}' " +
                               "(name collision after PascalCase conversion).");
                continue;
            }

            if (busName.Contains(','))
            {
                GD.PushWarning($"Anvil: Audio bus '{busName}' contains a comma and was excluded from HintString " +
                               "(would corrupt the enum hint string).");
            }
            else
            {
                busNames.Add(busName);
            }

            sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{busName}\";");
        }

        sb.AppendLine();
        sb.AppendLine($"{ind2}public const string HintString = \"{string.Join(',', busNames)}\";");

        sb.AppendLine($"{ind1}}}");
        sb.AppendLine();
    }

    private static void AppendGlobalGroupsClass(StringBuilder sb)
    {
        string ind1 = "    ";
        string ind2 = ind1 + "    ";

        sb.AppendLine($"{ind1}public static class GlobalGroups");
        sb.AppendLine($"{ind1}{{");

        List<string> groupNames = [];
        var seenNames = new HashSet<string>();

        foreach (Godot.Collections.Dictionary property in ProjectSettings.Singleton.GetPropertyList())
        {
            string settingName = property["name"].AsString();
            if (!settingName.StartsWith("global_group/"))
                continue;

            string groupName = settingName["global_group/".Length..];
            if (string.IsNullOrWhiteSpace(groupName))
                continue;

            string pascalCaseName = groupName.ToPascalCase();

            if (!seenNames.Add(pascalCaseName))
            {
                GD.PushWarning($"Anvil: Skipped duplicate global group ID '{pascalCaseName}' from '{groupName}' " +
                               "(name collision after PascalCase conversion).");
                continue;
            }

            if (groupName.Contains(','))
            {
                GD.PushWarning($"Anvil: Global group '{groupName}' contains a comma and was excluded from HintString " +
                               "(would corrupt the enum hint string).");
            }
            else
            {
                groupNames.Add(groupName);
            }

            sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{groupName}\";");
        }

        sb.AppendLine();
        sb.AppendLine($"{ind2}public const string HintString = \"{string.Join(',', groupNames)}\";");

        sb.AppendLine($"{ind1}}}");
        sb.AppendLine();
    }

    private static void AppendInputActionsClass(StringBuilder sb)
    {
        string ind1 = "    ";
        string ind2 = ind1 + "    ";

        sb.AppendLine($"{ind1}public static class InputActions");
        sb.AppendLine($"{ind1}{{");

        List<string> actionNames = [];
        var seenNames = new HashSet<string>();

        foreach (Godot.Collections.Dictionary property in ProjectSettings.Singleton.GetPropertyList())
        {
            string settingName = property["name"].AsString();
            if (!settingName.StartsWith("input/"))
                continue;

            string actionName = settingName["input/".Length..];
            if (string.IsNullOrWhiteSpace(actionName))
                continue;

            if (actionName.StartsWith("ui_"))
                continue;

            string pascalCaseName = actionName.ToPascalCase();

            if (!seenNames.Add(pascalCaseName))
            {
                GD.PushWarning($"Anvil: Skipped duplicate input action ID '{pascalCaseName}' from '{actionName}' " +
                               "(name collision after PascalCase conversion).");
                continue;
            }

            if (actionName.Contains(','))
            {
                GD.PushWarning($"Anvil: Input action '{actionName}' contains a comma and was excluded from HintString " +
                               "(would corrupt the enum hint string).");
            }
            else
            {
                actionNames.Add(actionName);
            }

            sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{actionName}\";");
        }

        sb.AppendLine();
        sb.AppendLine($"{ind2}public const string HintString = \"{string.Join(',', actionNames)}\";");

        sb.AppendLine($"{ind1}}}");
        sb.AppendLine();
    }

    private static void AppendFolderClass(StringBuilder sb, AnvilRule rule)
    {
        string ind1 = "    ";
        string ind2 = ind1 + "    ";

        sb.AppendLine($"{ind1}public static class {rule.OutputName}");
        sb.AppendLine($"{ind1}{{");

        string dirPath = ProjectSettings.GlobalizePath(rule.SourceFolder);
        List<string> generatedNames = [];

        var searchOption = rule.Recursive ? SearchOption.AllDirectories : SearchOption.TopDirectoryOnly;

        var files = Directory.GetFiles(dirPath, "*", searchOption)
            .Where(f => !ExcludedExtensions.Contains(Path.GetExtension(f).ToLower()));

        var seenNames = new HashSet<string>();

        foreach (var file in files)
        {
            string fileName = Path.GetFileNameWithoutExtension(file);
            string pascalCaseName = fileName.ToPascalCase();

            if (!seenNames.Add(pascalCaseName))
            {
                GD.PushWarning($"Anvil: Skipped duplicate ID '{pascalCaseName}' from '{file}' " +
                               $"(name collision within '{rule.SourceFolder}' after recursive scan).");
                continue;
            }

            if (rule.Mode == ForgeMode.FullPath)
            {
                string relativePath = Path.GetRelativePath(dirPath, file).Replace('\\', '/');
                string resPath = $"{rule.SourceFolder.TrimEnd('/')}/{relativePath}";

                sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{resPath}\";");
            }
            else
            {
                if (fileName.Contains(','))
                {
                    GD.PushWarning($"Anvil: '{fileName}' contains a comma and was excluded from HintString " +
                                   $"(would corrupt the enum hint string).");
                }
                else
                {
                    generatedNames.Add(fileName);
                }

                sb.AppendLine($"{ind2}public static readonly StringName {pascalCaseName} = \"{fileName}\";");
            }
        }

        if (rule.Mode == ForgeMode.Id)
        {
            sb.AppendLine();
            sb.AppendLine($"{ind2}public const string HintString = \"{string.Join(',', generatedNames)}\";");
        }

        sb.AppendLine($"{ind1}}}");
        sb.AppendLine();
    }
}
#endif
