using Godot;
using Anvil; // Namespace of the plugin

namespace Examples;

public partial class Audio : Node
{
    //You can export a list of generated ids for a specific use.

    /*
    [Export(PropertyHint.Enum, Audio.SfxNames.EnumNames)]
    public string CurrentSfx { get; set; }
    */

    // Works as a storage for sfx ids
    [Forge("res://addons/Anvil/examples/audio_files/sfx/", mode: ForgeMode.FullPath)]
    public static partial class SfxName;
}

//===============================================================
// Generated Script would look like this (during full path mode):
//===============================================================

/*
// AUTO-GENERATED BY ANVIL PLUGIN - DO NOT EDIT
using Godot;
using System;

namespace Examples;

public partial class Audio
{
    public static partial class SfxName
    {
        public static readonly StringName Digging = "res://addons/examples/audio_files/sfx/digging.mp3";
        public static readonly StringName Planted = "res://addons/examples/audio_files/sfx/planted.mp3";
        public static readonly StringName RockHit = "res://addons/examples/audio_files/sfx/rock_hit.mp3";
    }
}
*/
